from __future__ import annotations

from contextlib import AbstractAsyncContextManager
from typing import Protocol
from uuid import UUID

from ..models import FxRate, PortfolioSnapshot, Quote, Transaction


class PortfolioRepository(Protocol):
    async def connect(self) -> None: ...

    async def close(self) -> None: ...

    async def ping(self) -> bool: ...

    def transaction_lock(self) -> AbstractAsyncContextManager[None]: ...

    async def list_transactions(self) -> list[Transaction]: ...

    async def get_transaction(self, transaction_id: UUID) -> Transaction | None: ...

    async def save_transaction(self, transaction: Transaction) -> None: ...

    async def delete_transaction(self, transaction_id: UUID) -> bool: ...

    async def get_quotes(self, symbols: list[str]) -> dict[str, Quote]: ...

    async def save_quotes(self, quotes: list[Quote]) -> None: ...

    async def get_fx_rate(self) -> FxRate | None: ...

    async def save_fx_rate(self, rate: FxRate) -> None: ...

    async def list_snapshots(self) -> list[PortfolioSnapshot]: ...

    async def save_snapshot(self, snapshot: PortfolioSnapshot) -> None: ...

    async def replace_snapshots(self, snapshots: list[PortfolioSnapshot]) -> None: ...
